[JS2-785] Parallel Rendering on Websphere 6.1
In David's testings, we found this problem:
java.util.ConcurrentModificationException: concurrent access to HashMap attempted by Thread[WORKER_23,5,Workers]
	at java.util.HashMap.onEntry(HashMap.java:205)
	at java.util.HashMap.transfer(HashMap.java:510)
	at java.util.HashMap.resize(HashMap.java:500)
	at java.util.HashMap.addEntry(HashMap.java:800)
	at java.util.HashMap.put(HashMap.java:441)
	at com.ibm.ws.webcontainer.srt.SRTServletRequest.setAttribute(SRTServletRequest.java:466)
	at org.apache.jetspeed.container.invoker.AdjustedSRTServletRequest.setAttribute(AdjustedSRTServletRequest.java)

IMO, because SRTServletRequest#getAttribute() and SRTServletRequest#getAttributeNames() was not synchronized, the internal HashMap, _attributes threw ConcurrentModificationException.

git-svn-id: http://svn.apache.org/repos/asf/portals/jetspeed-2/branches/JETSPEED-2.1.3@587753 13f79535-47bb-0310-9956-ffa450edef68