JS2-938: Fixes some NPEs to see pages running. Currently, the remaining things is to fix the following NPE:
javax.portlet.PortletException: java.lang.NullPointerException
	at org.apache.jetspeed.container.invoker.LocalPortletInvoker.invoke(LocalPortletInvoker.java:169)
	at org.apache.jetspeed.container.invoker.JetspeedPortletInvokerService.rende
	...

The above NPE seems occurring because servletRequest is not passed via init() in PortletRequestContext propertly.

git-svn-id: http://svn.apache.org/repos/asf/portals/jetspeed-2/portal/trunk@758307 13f79535-47bb-0310-9956-ffa450edef68